.circleci/config.yml

Adding circleci integration. 
@alranel still need to add target rsync domain and folder. 
Thanks.

Add circleci ci-cd

---

AUTHORS
LICENSE
README.md
package.json

License change, authors list populated.

Changed license to AGPLv3.0 or later

---

src/app/components/head.js
src/app/contents/fields/generic.js
src/app/editor_generator_schema.json
src/app/yaml_validation_schema.json

Fixing several issues related to the names.

Fix naming issues

---

src/app/utils/validate.js

Fix a few typos in the schema name.

Typos in schema name

---

src/app/components/sidebar.js
src/asset/sidebar.scss

Issue #8: disabled download button

Issue 8: null file generated on empty editor

---

src/asset/editor_widget.scss
src/asset/language_switcher.scss

Fixed-Bug 
Added an Overflow property to the text-area content and added min-height and margin properties.
Suggestions Appreciated

Issue : #7

---

.circleci/config.yml

This PR introduces a new stage for linting and testing for branches != master

feat: added test stage for branches different than master

---

src/app/form/widgets/RemoteSearchWidget.js

New version now has:
- Text search on administration name / office name / ipa code / office code.
- The box should show one of the following (depending on the selection):
- administration name (administration ipa code)
- office name (administration ipa code)

New IPA logic as specified in #59

---

src/app/contents/fields/it.js
src/app/form/widgets/RemoteSearchWidget.js

- Query are now enforced and more specific on what user is searching for
- Field style now looks cleaner
- Search results are now limited to keep browser performance

Riuso - Codice IPA

---

src/app/contents/fields/generic.js
src/app/contents/fields/index.js
src/app/contents/fields/it.js

Fields are rearranged following #55 suggested flow

Reorganized fields by following hints on #55

---

package.json
src/app/contents/fields/generic.js
src/app/form/widgets/PhoneWidgets.js
src/app/form/widgets/index.js
src/asset/content.scss
yarn.lock

As already discussed in https://github.com/italia/publiccode-parser-go/pull/18 and #89  due to that YAML format ambiguity we came to decision to enforce phone field using international standard E.164.
Field will looks like:

Phone international format ready field in Maintenance->Contacts

---

src/app/contents/fields/it.js
src/app/form/widgets/RemoteSearchWidget.js

IPA Query are now based on new `indicepa_pec` elastic index, which contains more informations.
Fixes #83

Using new ES index

---

src/app/contents/fields/generic.js

Show the max length counter for features inputs.

---

src/app/form/widgets/CheckboxWidget.js
src/app/form/widgets/ChoiceExpandedWidget.js

Make checkbox and radio labels a clickable target to enlarge
the useful area the user can interact with.

Make checkbox and radio labels a clickable target.

---

src/app/components/CloseButton.js
src/app/components/InfoBox.js
src/app/components/languageSwitcher.js
src/app/form/widgets/ArrayWidget.js
src/asset/close_button.scss
src/asset/language_switcher.scss
src/asset/style.scss

Create the CloseButton component and make it behave consistently,
with a visual feedback on hover.

Show the close button is interactive.

---

src/app/form/widgets/ArrayWidget.js

Show the descriptions for ArrayWidget elements.

---

README.md

Just some small improvements on the README.

polishing: removed some linebreaks, added links, fixed typos

---

src/app/editor_generator_schema.json

Mostly small fixes: only one important (output -> input). Otherwise some uncountables, typos, some minor punctuation and whitespace.

fix: some typos and language

---

yarn.lock

See https://github.com/italia/publiccode-editor/pull/131#discussion_r396346912

Sync yarn.lock with package.json.

---

.circleci/config.yml
package.json
yarn.lock

Deploy to the gh-pages branch.

---

src/app/components/editorForm.js

This should fix #164. I'm not able to reproduce it locally, even in production mode though.

Fix undefined dereference.

---

package.json
src/app/form/widgets/BaseInputWidget.js
yarn.lock

Debounce input fields to reduce input lag.

---

src/app/contents/__tests__/licenses.test.js
src/app/contents/licenses.js

fixes #252
This commit also includes a test which compares against the current list provided by upstream.
Co-authored-by: @Ainali

Add remaining licenses from spdx.org

---

yarn.lock

update caniuse dependency
Closes #162

fix: warning message during build

---

.github/workflows/deploy.yml
.github/workflows/test.yml

feat(cd): migrate to GitHub Actions

---

package-lock.json
package.json
src/app/form/widgets/BaseInputWidget.js
src/app/form/widgets/CheckboxWidget.js
src/app/form/widgets/ChoiceExpandedWidget.js
src/app/form/widgets/ChoiceMultipleExpandedWidget.js
src/app/form/widgets/ChoiceWidget.js
src/app/form/widgets/ComboBoxWidget.js
src/app/form/widgets/DateTimeReactWidget.tsx
src/app/form/widgets/EditorWidget.js
src/app/form/widgets/FileWidget.js
src/app/form/widgets/MoneyWidget.js
src/app/form/widgets/PercentWidget.js
src/app/form/widgets/PhoneWidgets.js
src/app/form/widgets/RemoteSearchWidget.js
src/app/form/widgets/TagWidget.js
src/app/form/widgets/TextareaWidget.js

Loosely based on c300336528477fc323112ccaba3ea7774ad809c4.

build(deps): bump react-hook-form to 7.45.0

---

src/i18n/publiccode.json

Fix typo s/i/I

---

package-lock.json
package.json
src/app/app.tsx
src/app/form/widgets/BaseInputWidget.js
src/asset/style.scss

The major visual change is forms having floating labels. However there is still an issue with few labels overlapping with the corresponding inputs.
Fixes #286.

feat: use Bootstrap Italia design system

---

src/app/components/Head.tsx
src/app/contents/constants.ts
src/i18n/translations.json

The link is too visible and also only in Italian. Besides, the data stays on the client side.

fix: remove privacy policy link

---

src/i18n/index.ts
src/i18n/locales/fr.json

Import @garronej's translation from
https://github.com/codegouvfr/publiccode-editor/commit/b02931a45c519416babe24216856415867c4b0ab
https://github.com/codegouvfr/publiccode-editor/blob/2a807b98de5e99207ca1f6a17c4a7d6c71deadad/src/app/i18n/translations.js
Fix #229.
Partially implement #92.

feat: add French translation

---

src/app/components/Head.tsx
src/app/contents/constants.ts
src/asset/content.scss
src/i18n/locales/en.json
src/i18n/locales/fr.json
src/i18n/locales/it.json

fix: change links in the header

---

src/app/components/Info.tsx
src/i18n/locales/en.json
src/i18n/locales/fr.json
src/i18n/locales/it.json

Remove "Read more" from fields and shorten some Italian translation strings.

feat: remove read more from fields

---

src/app/form/widgets/ComboBoxWidget.js
src/app/form/widgets/DateTimeReactWidget.tsx
src/app/form/widgets/EditorWidget.js
src/app/form/widgets/TagWidget.js

Fix labels overlapping widgets for non design-react-kit widgets.

fix: labels overlapping widgets

---

src/app/form/widgets/ComboBoxWidget.js

fix: properly search for licenses in the combo box

---

src/app/components/Foot.tsx
src/i18n/locales/en.json
src/i18n/locales/fr.json
src/i18n/locales/it.json

Add translation string and fix Italian.

feat: add translation string for upload button

---

.dockerignore
Dockerfile
README.md

Also, copy patches/ into the build stage image, so patch-package can apply the patch properly.
Fix #311.

fix: build the Docker image and update the doc

---

src/i18n/index.ts
src/i18n/locales/de.json

Add a german json file for translation the amazing editor. 2nd try.
close https://github.com/italia/publiccode-editor/issues/403

Add german localisation

---

src/app/components/Head.tsx

added i18n for labels on header bar

fix: added i18n for labels on header bar

---

index.html
vite.config.ts

fix: warning on build fixed

---

.devcontainer/devcontainer.json
src/app/lib/utils.ts
src/app/linter/index.ts
src/app/linter/remove-empty.spec.ts
src/app/linter/remove-empty.ts

fix(#449): fix empty string serialization in yaml

---

src/app/components/Editor.tsx
src/app/publiccode-adapter.ts

fix: fixed validation problem on maintenance

---

src/app/components/Editor.tsx

497 warning with empty key

---

src/app/components/EditorAwards.tsx
src/app/components/EditorFeatures.tsx
src/app/components/EditorScreenshots.tsx
src/app/components/EditorVideos.tsx
src/assets/main.css

The list UI components for Awards, Features, Screenshots, and Videos have been redesigned with a chip-based interface following the [doc](https://designers.italia.it/design-system/componenti/chips/) about the Design System.
---
- **Chip-based List UI**: Replaced traditional list displays with modern chip components for Awards, Features, Screenshots, and Videos
- **Enhanced Video Previews**: Implemented responsive video preview system with proper aspect ratio management and oEmbed integration
---
No breaking changes introduced. All existing functionality is preserved while enhancing the user interface.
---
1. **Awards Management**: Use chips to display and manage award entries with easy removal
2. **Features List**: Organize software features using the new chip-based interface
3. …

feat/413: new list UI features screenshots videos awards
