italia/publiccode-editor

- .dockerignore
- .eslintrc
- Dockerfile
- package.json
In order to release the first version (0.1.0) here you may find the relevant checklist:
> Prepare for release 0.1.0

- package.json
Fixing the linter. Now we get:  
`✖ 56 problems (15 errors, 41 warnings)`.
Probably is better to fix them in this PR and then merge.
> fix: linter in package.json

- src/app/contents/fields/generic.js
- src/app/utils/validate.js
Publiccode specs for monochromeLogo and logo allows only image formats with transparent channel.
More info on #57. 
Any file field can be restricted to a preset file extensions list.
> File extensions validator

- .circleci/config.yml
Removed master from testing with cci.
However, I'm not so convinced about this since I'd like to run the test on master before continuing just in case (e.g., someone pushes directly to master). 
@sebbalex should we copy-paste the same "tests" lines used in `build-and-test` also in the `build-and-deploy`?
Which are this ones btw https://github.com/italia/publiccode-editor/blob/63e855ae5b04107354e3cdcf9ade3885a9dbb8ae/.circleci/config.yml#L47-L50
What do you think?
> Remove master from testing with cci

- src/app/components/languageSwitcher.js
- src/asset/language_switcher.scss
Make clear to the user that elements in the language switcher
are interactive and clickable.
> Use cursor: pointer in the language switcher.

- src/asset/editor_widget.scss
As pointed out by @bfabio in #98 when a long line in `longDescription` will breaks the layout with an unexpected container horizontal grows.
> Forced break-words for long line

- src/asset/content.scss
- src/asset/language_switcher.scss
Shrink the header to leave more space to the actual content and add an
accent color to subtly hint it's a fixed element.
Fix #74.
What do you think?
> Shrink the header and add an accent color to it.

- src/app/components/editor.js
Removing a language is a destructive action: show a confirmation dialog
to the user before taking action.
> Show confirmation dialog when removing a language.

- .circleci/config.yml
- src/app/app.js
- src/app/components/_layout.js
- src/app/components/editor.js
- src/app/components/editorForm.js
- src/app/components/sidebar.js
- src/app/contents/constants.js
- src/app/utils/calls.js
- src/asset/wrapper.scss
- webpack.config.js
- webpack.config.prod.js
This PR is intended to implement a more consistent way of validate publiccode as specified in #32 here we will collect data, tests and debate.
External validation using same library used by crawler to be more consistent. It is accomplished through a [proxy](https://github.com/italia/pc-web-validator) service who exposes rest API to interoperate.
- It will be exported always the latest `publiccodeYmlVersion` version
- Some keys could be tuned agreeing latest publiccodeYmlVersion specs.
- It adds a network layer of validation for fields who is required such as `url`, `apiDocumentation` and so on.
- `logo` and `screenshots`  are checked as well for their presence.
- It adds a little overhead due to remote checks, a loading mask is there for the purpose.
Fixes also #87, #86, #69, #65
#56?
And …
> External validation by GO parser

- src/asset/sidebar.scss
@libremente I have removed `cursor: pointer;` from the [sidebar.scss](https://github.com/italia/publiccode-editor/blob/master/src/asset/sidebar.scss) file.
> Remove pointer cursor from buttons in sidebar #126

- src/app/form/widgets/ComboBoxWidget.js
PR #118 introduced a human readable value for Combobox component but the entire object was sent to redux store instead of single value selected.
As for #133 validation breaks the entire Editor since data returned from ext validator was unreadable from editor itself. We should also consider to manage those kind of data, I will track it with a dedicated issue.
> Editor breaks on license change

- Dockerfile
Fail if yarn.lock is not up to date in order to allow
reproducible builds.
(needs #135 merged in)
> Always use dependencies versions from yarn.lock.

- src/app/components/editor.js
- src/app/components/sidebar.js
- src/app/contents/constants.js
- src/app/utils/calls.js
- webpack.config.js
As for #95 Editor should be capable to import publiccodes by their remote url. We will use the external validator to tackle cors exceptions due to differents code hosting platform and domains (some could be on premises with custom CORS rules).
> Editor will import publiccodes by their remote url

- src/app/components/sidebar.js
- src/app/utils/calls.js
Bubble up the validator errors to the user and handle non 2xx responses.
Also don't clean the state before validating, because when the
validation fails the app is left awkwardly empty.
> Handle remote validator errors.

- .circleci/config.yml
This just removes the noise in the CircleCI app: the pipeline
doesn't start anyway because there's no CircleCI config on
the gh-pages branch.
> Don't try to run CI when pushing to gh-pages.

- src/app/utils/calls.js
Using validation by URL, both as search param or with load url component, results in a white page with no content displayed.
> fix: remote validation was not working correctly using url param and load by url

- package.json
- patches/js-yaml+3.14.0.patch
- src/app/components/editor.js
- src/app/components/index.js
- yarn.lock
Literal blocks allow us to preserve newlines correctly.
Use patch-package to patch js-yaml until a proper solution
reaches upstream.
Fix #51.
> Force the use of literal blocks when dumping the YAML.

- .circleci/config.yml
- src/app/components/editorForm.js
- src/app/contents/data.js
This will highlight also sub-properties in validation process, this is mostly due to divergent ways to call fields between form and go-validator.
It is not ready for merge since exists a bug in parser/external validator:
https://github.com/italia/publiccode-validator/issues/10
Fixes:
#87
> Sub-properties are now highlighted when in error

- .github/workflows/publiccode-validation.yml
Use the right GitHub Action name for the publiccode validation workflow.
> chore: fix the publiccode validation workflow

- .circleci/config.yml
Use yarn install --frozen-lockfile to install dependencies from
the lockfile instead of updating it.
> chore: install dependencies from the lockfile

- src/i18n/publiccode.json
Simplified fields descriptions in the UI, uniformed styles and
contextualized messages. In particular:
* Consistently use typography quotes
* Remove length and other requirements from the description when the UI
is already making those clear via other means.
* Remove redundant and potentially confusing terminology whose meaning
fades at the UI level (eg. "This key")
* Use "Free and Open Source" instead of just "Open Source"
> Simplified fields descriptions in the UI.

- src/asset/style.scss
This is caused by the use of Bootstap Italia.
> fix: do not overlap label and input elements

- src/app/form/widgets/TagWidget.js
Match when the search term is not at the start of the tag as well.
Fix #184.
> fix: better search in tags widgets

- src/app/form/widgets/BaseInputWidget.js
- src/app/form/widgets/ChoiceExpandedWidget.js
`innerRef` provides a reference to the internal `<input>` element.
> fix: use `innerRef` in design-react-kit `Input` component

- .devcontainer/postCreateCommand.sh
- src/app/yaml-upload.spec.ts
- src/app/yaml-upload.ts
- **Operating System:** Windows 11
- **Browsers:** Chrome, Firefox, Edge
On **Windows 11**, when selecting `.yml` or `.yaml` files via the file dialog in a browser, the `file.type` is often empty. This caused issues with proper YAML file recognition, especially when the MIME type isn't automatically detected by the browser.
- **Handling empty MIME types:** We added a check for cases where `file.type` is empty and the user is on Windows. In these cases, we fall back to checking the file extension (either `.yml` or `.yaml`) to determine if the file is a YAML file.
- **Updated `isYamlFile` function:** The logic now correctly handles cases where `file.type` is empty, ensuring proper YAML file recognition on Windows.
- **Improved tests:** We updated and expanded the tests to account for …
> 389 file non supportato

- src/i18n/index.ts
As stated in the [i18next documentation](https://www.i18next.com/overview/configuration-options), setting the `lng` parameter overrides the language detection.
Closes #388
> fix: remove default language to allow language detection

- package-lock.json
- package.json
bump version for the following package:
- @peterek/vite-plugin-favicons
- @vitejs/plugin-react
- tsx
- vite
PR #396 is no longer needed.
> build(deps): bump vite version

- src/app/components/Editor.tsx
The `publiccodeYmlVersion` field is no longer incorrectly displayed when uploading a `publiccode.yml` file with version `0.4`. The issue was caused by a mismatch in version recognition—`0.4` was not being correctly interpreted as equivalent to `0.4.0`. A stricter semantic versioning (semver) check has been implemented to handle this properly.
---
Improved version detection with semantic versioning logic.  
Now supports both `0.4` and `0.4.0` as equivalent.
---
No breaking changes introduced.
> fix/437: yml version visibility behavior

- src/app/components/EditorScreenshots.tsx
- src/app/components/EditorUsedBy.tsx
- src/app/components/EditorVideos.tsx
The issue was caused by missing `type` attribute on the info button: since they default to `submit`, they were unintentionally triggering the form submission.
Closes #450
> fix(#450): avoid page reload on info icon click

- src/app/components/Editor.tsx
Fixed a critical bug where loading an invalid YAML file after a valid one would silently keep the previous valid data and show misleading "Validation completed with success" message.
---
- **Fixed Import State Management**: Editor now properly clears previous form data before attempting to load a new file
---
No breaking changes introduced. This is a bug fix that improves existing functionality.
> fix/512: reset validation on import
